[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
childlogdir=/app/logs

[program:redis]
command=redis-server
autostart=true
autorestart=true

[program:backend]
command=uvicorn main:app --host 0.0.0.0 --port 10000 --proxy-headers --forwarded-allow-ips '*'
directory=/app/apps/backend
autostart=true
autorestart=true
stdout_logfile=/app/logs/backend.log
stderr_logfile=/app/logs/backend_err.log

[program:worker]
command=celery -A tasks worker --loglevel=info --concurrency=2
directory=/app/apps/backend
autostart=true
autorestart=true
stdout_logfile=/app/logs/worker.log
stderr_logfile=/app/logs/worker_err.log
